<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();


function console_log( $data ){
  echo '<script>';
  echo 'console.log('. json_encode( $data ) .')';
  echo '</script>';
}

console_log($itemMedia);
?>
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php $this->trigger('view.show.before'); ?>
<?php if ($embedMedia && $itemMedia): ?>
    <div class="media-embeds">
    <?php foreach ($itemMedia as $media):
        echo $media->render();
    endforeach;
    ?>
    </div>
<?php endif; ?>
<?php echo $item->displayValues(); ?>
<div class="property">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
        <h4><?php echo $translate('Item sets'); ?></h4>
        <?php foreach ($itemSets as $itemSet): ?>
            <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<div class="property">
    <h4>Citation</h4>
    <div class="values">
        <div class="value" lang="">
            <?php echo $item->displayTitle() . 
                "Slavery Images: A Visual Record of the African Slave Trade and Slave Life in the Early African Diaspora, accessed " . 
                date("F j, Y") .
                ", " .
                "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>
        </div>
    </div>
</div>

<?php if (!$embedMedia && $itemMedia): ?>
<div class="media-list">
    <?php foreach ($itemMedia as $media): ?>
        <?php 
            $manifest_url = $this->iiifUrl($item) ;
            $mirador_url = $item->url() . '/mirador';
        ?>
        <?php console_log($media->linkPretty()); console_log($media->mediaType()); ?>
        <?php if(preg_match('/\bimage\b/', $media->mediaType())):  ?>
            <a href="<?php echo $mirador_url; ?>" target="_blank">
              <?php echo $media->render(['link' => null, 'thumbnailAttribs' => ['alt' => $item->displayDescription()]]); ?>
            </a>
            <a href="<?php echo $manifest_url; ?>" target="_blank"><img src="<?php echo $this->assetUrl('images/logo-iiif.png') ?>" alt="IIIF Manifest">
            </a>
            <a href="<?php echo $media->originalUrl(); ?>"><img src="<?php echo $this->assetUrl('images/download.png') ?>" alt="Download"></a>
        <?php elseif(preg_match('/\bpdf\b/', $media->mediaType())): ?> 
        <?php echo $media->render(); ?>
        <?php else: ?> 
            <?php $media->linkPretty(); ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

<?php endif; ?>


<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>